apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
data:
  PYTHONPATH: "/app"
  RUNNING_IN_DOCKER: "false"
  DATABASE_URL: "postgresql://postgres:postgres@db:5432/portfolio_db"
  TEST_DATABASE_URL: "postgresql://postgres:postgres@db-test:5432/portfolio_test_db"
  REDIS_URL: "redis://redis:6379/0"
