apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fastapi-rolebinding
  namespace: cloudnative-devops
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: fastapi
    meta.helm.sh/release-namespace: cloudnative-devops
subjects:
- kind: ServiceAccount
  name: fastapi-sa
  namespace: cloudnative-devops
roleRef:
  kind: Role
  name: fastapi-role
  apiGroup: rbac.authorization.k8s.io
