apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi-sa
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: fastapi
    meta.helm.sh/release-namespace: cloudnative-devops
  namespace: cloudnative-devops