apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cloudnative-devops
  name: fastapi-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
