apiVersion: v1
kind: Namespace
metadata:
  name: cloudnative-devops
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: fastapi
    meta.helm.sh/release-namespace: cloudnative-devops