apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  DATABASE_URL: {{ .Values.postgres.databaseUrl | quote }}
