apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.postgres.storage | quote }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres
