apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    storage-target: postgres
spec:
  capacity:
    storage: {{ .Values.postgres.storage | quote }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /data/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cloudnative-cluster-control-plane
