apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-test
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-test
  template:
    metadata:
      labels:
        app: postgres-test
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: postgres-test
        image: {{ .Values.postgres.image | quote }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password | quote }}
        - name: POSTGRES_DB
          value: portfolio_test_db
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata  # Fixes the 'Operation not permitted' error
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-test-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-test-storage
        emptyDir: {}
