apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.redis.storage | quote }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/redis
