name: Publish Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          IMAGE_BASE=ghcr.io/${{ github.repository }}/app
          IMAGE_BASE=$(echo $IMAGE_BASE | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_BASE:latest .
          docker tag $IMAGE_BASE:latest $IMAGE_BASE:${{ github.sha }}

      - name: Security scan with Trivy
        uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: ghcr.io/${{ github.repository }}/app:latest
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true

      - name: Push image
        run: |
          IMAGE_BASE=ghcr.io/${{ github.repository }}/app
          IMAGE_BASE=$(echo $IMAGE_BASE | tr '[:upper:]' '[:lower:]')
          docker push $IMAGE_BASE:latest
          docker push $IMAGE_BASE:${{ github.sha }}
